### ISSUE TITLE
DataItems

### ISSUE THREAD

**Issue by ghost** [jakubczaplicki/iTesa#5]
Should we change this to "PhoneDataItem" or magnetic or something?

I suppose we are guessing until we know what kind of stuff we'll be getting from STRaND, but what about telemetry data etc?

**Comment by jakubczaplicki** [comment]
"MagneticDataItem" would be better. Or something different at all. 

True. I completely forgot about other telemetry data. I'll think about it. 

I will also make a diagram of how the software is currently structured so that we've got overview of what we're doing. I must admit however that I don't do UML (I just don't get it) :)

**Comment by ghost** [comment]
I've never used UML before, but I can look into it if you want. 

I think a diagram is going to help things along nicely.
